=== ketrolynferreira/programacion-2020-2021/copia/Reto-1g-Sendy-Guille-Unai-main/xml/jornadas.dtd
<!ELEMENT jornadas (partido+)>
<!ELEMENT partido (NUM_JORNADA,HORA,RESULTADOL,RESULTADOV,ID_EQUIPOL,ID_EQUIPOV)>
<!ELEMENT NUM_JORNADA (#PCDATA)>
<!ELEMENT HORA (#PCDATA)>
<!ELEMENT RESULTADOL (#PCDATA)>
<!ELEMENT RESULTADOV (#PCDATA)>
<!ELEMENT ID_EQUIPOL (#PCDATA)>
<!ELEMENT ID_EQUIPOV (#PCDATA)>

=== ketrolynferreira/programacion-2020-2021/copia/Reto-1g-Sendy-Guille-Unai-main/xml/jornadas.xml
<?xml version="1.0" encoding="Cp1252"?>
<!DOCTYPE jornadas SYSTEM "jornadas.dtd">
<jornadas xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="jornadas.xsd">
 <partido>
  <NUM_JORNADA>1</NUM_JORNADA>
  <HORA>12/06/21 18:50:00,000000</HORA>
  <RESULTADOL>2</RESULTADOL>
  <RESULTADOV>3</RESULTADOV>
  <ID_EQUIPOL>2</ID_EQUIPOL>
  <ID_EQUIPOV>3</ID_EQUIPOV>
 </partido>
 <partido>
  <NUM_JORNADA>1</NUM_JORNADA>
  <HORA>12/06/21 19:50:00,000000</HORA>
  <RESULTADOL>3</RESULTADOL>
  <RESULTADOV>1</RESULTADOV>
  <ID_EQUIPOL>1</ID_EQUIPOL>
  <ID_EQUIPOV>5</ID_EQUIPOV>
 </partido>
 <partido>
  <NUM_JORNADA>2</NUM_JORNADA>
  <HORA>19/06/21 14:30:00,000000</HORA>
  <RESULTADOL>3</RESULTADOL>
  <RESULTADOV>0</RESULTADOV>
  <ID_EQUIPOL>4</ID_EQUIPOL>
  <ID_EQUIPOV>6</ID_EQUIPOV>
 </partido>
 <partido>
  <NUM_JORNADA>2</NUM_JORNADA>
  <HORA>19/06/21 16:30:00,000000</HORA>
  <RESULTADOL>3</RESULTADOL>
  <RESULTADOV>2</RESULTADOV>
  <ID_EQUIPOL>5</ID_EQUIPOL>
  <ID_EQUIPOV>2</ID_EQUIPOV>
 </partido>
 <partido>
  <NUM_JORNADA>3</NUM_JORNADA>
  <HORA>26/06/21 19:20:00,000000</HORA>
  <RESULTADOL>3</RESULTADOL>
  <RESULTADOV>1</RESULTADOV>
  <ID_EQUIPOL>6</ID_EQUIPOL>
  <ID_EQUIPOV>3</ID_EQUIPOV>
 </partido>
 <partido>
  <NUM_JORNADA>3</NUM_JORNADA>
  <HORA>26/06/21 21:20:00,000000</HORA>
  <RESULTADOL>0</RESULTADOL>
  <RESULTADOV>3</RESULTADOV>
  <ID_EQUIPOL>1</ID_EQUIPOL>
  <ID_EQUIPOV>4</ID_EQUIPOV>
 </partido>
 <partido>
  <NUM_JORNADA>4</NUM_JORNADA>
  <HORA>02/06/21 12:40:00,000000</HORA>
  <RESULTADOL>2</RESULTADOL>
  <RESULTADOV>3</RESULTADOV>
  <ID_EQUIPOL>6</ID_EQUIPOL>
  <ID_EQUIPOV>5</ID_EQUIPOV>
 </partido>
</jornadas>
